// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace net {
	
	
	public partial class _Default {
		
		protected System.Web.UI.WebControls.Content HeaderContent;
		
		protected System.Web.UI.WebControls.Literal title;
		
		protected System.Web.UI.WebControls.Content BodyContent;
		
		protected System.Web.UI.WebControls.Literal greeting;
		
		protected System.Web.UI.WebControls.Literal footer1_1;
		
		protected System.Web.UI.WebControls.Literal f2;
		
		protected System.Web.UI.WebControls.HiddenField cultureVal;
	}
}
