// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace net {
	
	
	public partial class SiteMaster {
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl htm;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder titleContent;
		
		protected System.Web.UI.WebControls.ImageButton egyCulture;
		
		protected System.Web.UI.WebControls.ImageButton rusCulture;
		
		protected System.Web.UI.WebControls.ImageButton gerCulture;
		
		protected System.Web.UI.WebControls.ImageButton spanCulture;
		
		protected System.Web.UI.WebControls.ImageButton engCulture;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder MainContent;
	}
}
